ALTER TABLE STG_FORCTX DROP COLUMN CTX_NUMRMI_OLD;
ALTER TABLE STG_FORCTX DROP COLUMN CTX_NUMRMX_OLD;

ALTER TABLE STG_ANETRA DROP COLUMN ANE_FIRMAR_OLD;
ALTER TABLE STG_ANETRA DROP COLUMN ANE_FIRMAD_OLD;
