# Conexion BBDD
jdbc.jndi=java:/es.caib.sistrahelp.db
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

# ENTORNO {des,pre,pro,se}
entorno=se
# URL STG
sistrages.rest.url=http://localhost:58080/sistragesws/rest/interna
sistrages.rest.user=api-stg
sistrages.rest.pwd=1234
sistrages.view.url=https://ibenred2.indra.es/sistragesback/secure/app

# URL SISTRAMIT
sistramit.rest.url=http://localhost:58080/sistramitws/rest/interna
sistramit.rest.user=api-stt
sistramit.rest.pwd=C4mp30n@s

# ALMACENAMIENTO FICHEROS
ficherosExternos.path=/opt/caib-data/sistra2-data/files_des

# Número de días que se restan a la fecha inicio en la búsqueda
filtroInicial=15

# Hora desde la que se evaluará en tiempo real los eventos del cuadro de mando en el día actual
horaDesde=00:00

# Minutos que tardará el cuadro de mando en refrescarse de forma automática
minutosRefresco=5

# Permite personalizar los umbrales de aviso en CM ( true / false )
permitirPersonalizarUmbralesCM=true

# Porcentajes de los umbrales que separan los valores de aviso "Normal", "Atención" y "Revisar" en el cuadro de mando
# 0% >= "Normal" < [umbralNormalAtencion]% >= "Atencion" < [umbralAtencionRevisar]% < "Revisar" >= 100%
umbralNormalAtencion=33
umbralAtencionRevisar=66

# URL PAYMENTIB
paymentib.view.url=https://ibenred2.indra.es/paymentibback/secure/app

# Script engine: javascript (defecto JDK, para JDK8 nashorn) / rhino
scriptEngine=rhino
