UPDATE SISTRAGES.STG_ANETRA
SET ANE_EXTPER = 'pdf', ANE_VALFIRM = 0
WHERE ANE_CODPTR IN (
    SELECT PTR_CODIGO
    FROM SISTRAGES.STG_PASOTR, stg_vertra
    WHERE PTR_CODVTR = VTR_CODIGO and VTR_AUTQAA in (1,2)
);

commit;