CREATE TABLE STG_FORTRA_BCK AS SELECT * FROM STG_FORTRA;
CREATE TABLE STG_ANETRA_BCK AS SELECT * FROM STG_ANETRA;

GRANT SELECT, DELETE, INSERT, UPDATE ON STG_FORTRA_BCK TO WWW_SISTRAGES;
GRANT SELECT, DELETE, INSERT, UPDATE ON STG_ANETRA_BCK TO WWW_SISTRAGES;
