UPDATE SISTRAGES.STG_ANETRA
SET ANE_EXTPER = 'pdf'
WHERE ANE_CODPTR IN (
    SELECT PTR_CODIGO
    FROM SISTRAGES.STG_PASOTR, stg_vertra
    WHERE PTR_CODVTR = VTR_CODIGO and VTR_AUTQAA = 1 and ANE_FIRMAR = 1
);

commit;