UPDATE SISTRAGES.STG_ANETRA
SET ANE_VALFIRM = 0
WHERE ANE_CODPTR IN (
    SELECT PTR_CODIGO
    FROM SISTRAGES.STG_PASOTR, stg_vertra
    WHERE PTR_CODVTR = VTR_CODIGO and VTR_AUTQAA = 1
);

UPDATE SISTRAGES.STG_ANETRA
SET ANE_VALFIRM = 1
WHERE ANE_CODPTR IN (
    SELECT PTR_CODIGO
    FROM SISTRAGES.STG_PASOTR, stg_vertra
    WHERE PTR_CODVTR = VTR_CODIGO and VTR_AUTQAA IN (2,3) and ANE_FIRMAR = 1
);

commit;