UPDATE SISTRAGES.STG_FORTRA fortra
SET fortra.FTR_FIRDIG = 0
WHERE EXISTS (
  SELECT 1
  FROM SISTRAGES.STG_VERTRA vertra
  JOIN SISTRAGES.STG_PASOTR paso ON vertra.VTR_CODIGO = paso.PTR_CODVTR
  JOIN SISTRAGES.STG_PASREL pasrel ON paso.PTR_CODIGO = pasrel.PRL_CODIGO
  JOIN SISTRAGES.STG_PRLFTR prlftr ON pasrel.PRL_CODIGO = prlftr.FPR_CODPRL
  WHERE prlftr.FPR_CODFOR = fortra.FTR_CODIGO
    AND vertra.VTR_NORMATIVA = 'E'
    AND vertra.VTR_AUTENO = 1
);

commit;