--Se hace copia de seguridad en las columnas nuevas
UPDATE SISTRAGES.STG_FORTRA SET FTR_FIRDIG_OLD = FTR_FIRDIG;
UPDATE SISTRAGES.STG_ANETRA SET ANE_FIRMAD_OLD = FTR_FIRMAD;
UPDATE SISTRAGES.STG_ANETRA SET ANE_FIRMAR_OLD = FTR_FIRMAR;
UPDATE SISTRAGES.STG_ANETRA SET ANE_VALFIRM_OLD = ANE_VALFIRM;
commit;
