

var intlTelInput_idioma = {
  ad: "Andorra",
  ae: "Emirats Àrabs Units",
  af: "Afganistan",
  ag: "Antigua i Barbuda",
  ai: "Anguila",
  al: "Albània",
  am: "Armènia",
  ao: "Angola",
  aq: "Antàrtida",
  ar: "Argentina",
  as: "Samoa americana",
  at: "Àustria",
  au: "Austràlia",
  aw: "Aruba",
  ax: "Illes Åland",
  az: "Azerbaidjan",
  ba: "Bòsnia i Hercegovina",
  bb: "Barbats",
  bd: "Bangladès",
  be: "Bèlgica",
  bf: "Burkina Faso",
  bg: "Bulgària",
  bh: "Baréin",
  bi: "Burundi",
  bj: "Benin",
  bl: "San Bartomeu",
  bm: "Bermudes",
  bn: "Brunei",
  bo: "Bolívia",
  bq: "Carib neerlandès",
  br: "Brasil",
  bs: "Bahames",
  bt: "Butan",
  bv: "Illa Bouvet",
  bw: "Botsuana",
  by: "Bielorússia",
  bz: "Belice",
  ca: "Canadà",
  cc: "Illes Cocos",
  cd: "República Democràtica del Congo",
  cf: "República Centreafricana",
  cg: "Congo",
  ch: "Suïssa",
  ci: "Côte d’Ivoire",
  ck: "Illes Cook",
  cl: "Xile",
  cm: "Camerun",
  cn: "Xina",
  co: "Colòmbia",
  cr: "Costa Rica",
  cu: "Cuba",
  cv: "Cap Verd",
  cw: "Curazao",
  cx: "Illa de Nadal",
  cy: "Xipre",
  cz: "Txèquia",
  de: "Alemanya",
  dj: "Djibouti",
  dk: "Dinamarca",
  dm: "Dominica",
  do: "República Dominicana",
  dz: "Algèria",
  ec: "Equador",
  ee: "Estònia",
  eg: "Egipte",
  eh: "Sàhara Occidental",
  er: "Eritrea",
  es: "Espanya",
  et: "Etiòpia",
  fi: "Finlàndia",
  fj: "Fiji",
  fk: "Illes Malvines",
  fm: "Micronèsia",
  fo: "Illes Fèroe",
  fr: "França",
  ga: "Gabon",
  gb: "Regne Unit",
  gd: "Granada",
  ge: "Geòrgia",
  gf: "Guaiana Francesa",
  gg: "Guernsey",
  gh: "Ghana",
  gi: "Gibraltar",
  gl: "Groenlàndia",
  gm: "Gàmbia",
  gn: "Guinea",
  gp: "Guadalupe",
  gq: "Guinea Equatorial",
  gr: "Grècia",
  gs: "Illes Geòrgia del Sud i Sandwich del Sud",
  gt: "Guatemala",
  gu: "Guam",
  gw: "Guinea-Bisau",
  gy: "Guyana",
  hk: "RAE de Hong Kong (Xina)",
  hm: "Illes Heard i McDonald",
  hn: "Hondures",
  hr: "Croàcia",
  ht: "Haití",
  hu: "Hongria",
  id: "Indonèsia",
  ie: "Irlanda",
  il: "Israel",
  im: "Illa de Man",
  in: "Índia",
  io: "Territori Britànic de l'Oceà Índic",
  iq: "Iraq",
  ir: "Iran",
  is: "Islàndia",
  it: "Itàlia",
  je: "Jersei",
  jm: "Jamaica",
  jo: "Jordània",
  jp: "Japó",
  ke: "Kenya",
  kg: "Kirguizistan",
  kh: "Cambodja",
  ki: "Kiribati",
  km: "Comores",
  kn: "Sant Cristòfol i Neus",
  kp: "Corea del Nord",
  kr: "Corea del Sud",
  kw: "Kuwait",
  ky: "Illes Caiman",
  kz: "Kazakhstan",
  la: "Laos",
  lb: "Líban",
  lc: "Santa Llúcia",
  li: "Liechtenstein",
  lk: "Sri Lanka",
  lr: "Libèria",
  ls: "Lesoto",
  lt: "Lituània",
  lu: "Luxemburg",
  lv: "Letònia",
  ly: "Líbia",
  ma: "Marroc",
  mc: "Mònaco",
  md: "Moldàvia",
  em: "Montenegro",
  mf: "Sant Martí",
  mg: "Madagascar",
  mh: "Illes Marshall",
  mk: "Macedònia del Nord",
  ml: "Mali",
  mm: "Myanmar (Birmània)",
  mn: "Mongòlia",
  mo: "RAE de Macau (Xina)",
  mp: "Illes Mariannes del Nord",
  mq: "Martinica",
  mr: "Mauritània",
  ms: "Montserrat",
  mt: "Malta",
  mu: "Maurici",
  mv: "Maldives",
  mw: "Malaui",
  mx: "Mèxic",
  my: "Malàisia",
  mz: "Moçambic",
  na: "Namíbia",
  nc: "Nova Caledònia",
  ne: "Níger",
  nf: "Illa Norfolk",
  ng: "Nigèria",
  ni: "Nicaragua",
  nl: "Països Baixos",
  no: "Noruega",
  np: "Nepal",
  nr: "Nauru",
  nu: "Niue",
  nz: "Nova Zelanda",
  om: "Oman",
  pa: "Panamà",
  pe: "Perú",
  pf: "Polinèsia Francesa",
  pg: "Papua Nova Guinea",
  ph: "Filipines",
  pk: "Pakistan",
  pl: "Polònia",
  pm: "Sant Pere i Miqueló",
  pn: "Illes Pitcairn",
  pr: "Puerto Rico",
  ps: "Territoris Palestins",
  pt: "Portugal",
  pw: "Palau-vos",
  py: "Paraguai",
  qa: "Catar",
  re: "Reunió",
  ro: "Romania",
  rs: "Sèrbia",
  ru: "Rússia",
  rw: "Rwanda",
  sa: "Aràbia Saudita",
  sb: "Illes Salomó",
  sc: "Seychelles",
  sd: "Sudan",
  se: "Suècia",
  sg: "Singapur",
  sh: "Santa Elena",
  si: "Eslovènia",
  sj: "Svalbard i Jan Mayen",
  sk: "Eslovàquia",
  sl: "Sierra Leone",
  sm: "San Marí",
  sn: "Senegal",
  so: "Somàlia",
  sr: "Surinam",
  ss: "Sudan del Sud",
  st: "Sant Tomé i Príncep",
  sv: "El Salvador",
  sx: "Sint Maarten",
  sy: "Síria",
  sz: "Esuatini",
  tc: "Illes Turques i Caicos",
  td: "Txad",
  tf: "Territoris Australs Francesos",
  tg: "Togo",
  th: "Tailàndia",
  tj: "Tadjikistan",
  tk: "Tokelau",
  tl: "Timor-Leste",
  tm: "Turkmenistan",
  tn: "Tunísia",
  to: "Tonga",
  tr: "Turquia",
  tt: "Trinitat i Tobago",
  tv: "Tuvalu",
  tw: "Taiwan",
  tz: "Tanzània",
  ua: "Ucraïna",
  ug: "Uganda",
  um: "Illes menors allunyades dels EUA",
  us: "Estats Units",
  uy: "Uruguai",
  uz: "Uzbekistan",
  va: "Ciutat del Vaticà",
  vc: "Sant Vicent i les Grenadines",
  ve: "Veneçuela",
  vg: "Illes Verges Britàniques",
  vi: "Illes Verges dels EUA",
  vn: "Vietnam",
  vu: "Vanuatu",
  wf: "Wallis i Futuna",
  ws: "Samoa",
  ye: "Iemen",
  yt: "Mayotte",
  za: "Sud-àfrica",
  zm: "Zàmbia",
  zw: "Zimbabwe"
};