ALTER TABLE SISTRAMIT.STT_TCKCDC MODIFY TCC_IDESTR NULL;
ALTER TABLE SISTRAMIT.STT_TCKCDC DROP COLUMN TCC_INFAUT;
ALTER TABLE SISTRAMIT.STT_TCKCDC ADD TCC_TIPO VARCHAR2(2) NOT NULL;
ALTER TABLE SISTRAMIT.STT_TCKCDC ADD TCC_INFAUT CLOB NOT NULL;
ALTER TABLE SISTRAMIT.STT_TCKCDC ADD TCC_INFFH CLOB NULL;
 
comment on column STT_TCKCDC.TCC_INFAUT is 'Información usuario autenticado';
comment on column STT_TCKCDC.TCC_INFFH is 'Información funcionario habilitado';
 
 
ALTER TABLE SISTRAMIT.STT_TRAPER ADD TRP_FHUSER VARCHAR2(100 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAPER ADD TRP_FHNIF VARCHAR2(10 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAPER ADD TRP_FHNOM VARCHAR2(1000 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAPER ADD TRP_FHAPE1 VARCHAR2(255 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAPER ADD TRP_FHAPE2 VARCHAR2(255 CHAR);
 
comment on column STT_TRAPER.TRP_FHUSER is 'Funcionario habilitado: Usuario';
comment on column STT_TRAPER.TRP_FHNIF is 'Funcionario habilitado: NIF';
comment on column STT_TRAPER.TRP_FHNOM is 'Funcionario habilitado: Nombre';
comment on column STT_TRAPER.TRP_FHAPE1 is 'Funcionario habilitado: Apellido 1';
comment on column STT_TRAPER.TRP_FHAPE2 is 'Funcionario habilitado: Apellido 2';
 
 
ALTER TABLE SISTRAMIT.STT_TRAFIN ADD TRF_FHUSER VARCHAR2(100 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAFIN ADD TRF_FHNIF VARCHAR2(10 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAFIN ADD TRF_FHNOM VARCHAR2(1000 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAFIN ADD TRF_FHAPE1 VARCHAR2(255 CHAR);
ALTER TABLE SISTRAMIT.STT_TRAFIN ADD TRF_FHAPE2 VARCHAR2(255 CHAR);
 
comment on column STT_TRAFIN.TRF_FHUSER is 'Funcionario habilitado: Usuario';
comment on column STT_TRAFIN.TRF_FHNIF is 'Funcionario habilitado: NIF';
comment on column STT_TRAFIN.TRF_FHNOM is 'Funcionario habilitado: Nombre';
comment on column STT_TRAFIN.TRF_FHAPE1 is 'Funcionario habilitado: Apellido 1';
comment on column STT_TRAFIN.TRF_FHAPE2 is 'Funcionario habilitado: Apellido 2';
 