update STG_CNFGLO set CFG_VALOR = '2' where cfg_prop = 'sistra2.version.patch';
/*** SENTENCIA PARA ACTUALIZAR LOS TRÁMITES QUE TENGAN EL CHECK DE VALIDA REPRESENTACIÓN MARCADO.***/
UPDATE STG_PASREG SET PRG_REPVAL=0 WHERE PRG_REPVAL=1;