jdbc.jndi=java:/es.caib.sistramit.db
hibernate.show_sql=true
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.hbm2ddl.auto=none

# {des,pre,pro,se}
entorno=se

# ALMACENAMIENTO FICHEROS
ficherosExternos.path=/opt/caib-data/sistra2-data/files_des

# PROCESOS
procesos.purga.cron=0 */10 * ? * *
procesos.invalidaciones.cron=0 * * * * ?
procesos.envios.reintentos.cron=0 0 0/1 * * ?
procesos.envios.inmediatos.cron=0 0/1 * * * ?
procesos.entregaTramitesFinalizados.inmediatos.cron=0 0/1 * * * ?
procesos.entregaTramitesFinalizados.periodicos.cron=0 0/15 * * * ?
procesos.funcionarioHabilitadoTramitesFinalizados.cron=0 0/5 * * * ?

# URL STG
sistrages.url=http://localhost:58080/sistragesws/rest/interna
sistrages.usr=api-stg
sistrages.pwd=1234


# Timeout de la sesi�n web del asistente (en minutos)
sesionweb.timeout=30

#Envios
envios.reintentos=3

# CSRF (sirve para deshabilitar CSRF para pruebas)
csrf.enabled=true

# Script engine: javascript (defecto JDK, para JDK8 nashorn) / rhino
scriptEngine=rhino

# URL para el correo de incidencias
sistrahelp.view.url=https://ibenred2.indra.es/sistrahelp/secure/app
