--Se eliminan las columnas creadas en versiones anteriores para guardar copia de datos
ALTER TABLE SISTRAGES.STG_ANETRA DROP COLUMN ANE_FIRMAR_OLD;
ALTER TABLE SISTRAGES.STG_ANETRA DROP COLUMN ANE_FIRMAD_OLD;

ALTER TABLE SISTRAGES.STG_VERTRA DROP COLUMN VTR_AUTMET_OLD;
