UPDATE SISTRAGES.STG_DOMINI
SET DOM_BDJNDI = REPLACE(DOM_BDJNDI, '.sistra.', '.sistrahelp.'),
    DOM_BDSQL = REPLACE(DOM_BDSQL, 'STR_', 'STH_')
WHERE DOM_IDENTI IN ('DOM-CCAA', 'ILLES_BALEARS', 'MUNICIPIS', 'MUNICIPIS_ILLA', 'PAISOS', 'PROVINCIES')
  AND DOM_AMBITO = 'G';
commit;