CREATE TABLE SISTRAHELP.STH_DCOMAU
(
  CAU_CODIGO NUMBER(2, 0) NOT NULL,
  CAU_DENCAS VARCHAR2(40 CHAR) NOT NULL,
  CAU_DENCAT VARCHAR2(40 CHAR) NOT NULL,
  CAU_DORCAS VARCHAR2(40 CHAR),
  CAU_DORCAT VARCHAR2(40 CHAR),
  CAU_DIRECC VARCHAR2(40 CHAR),
  CAU_CODPOS NUMBER(5, 0),
  CAU_CODPRO NUMBER(2, 0),
  CAU_CODMUN NUMBER(3, 0),
  CAU_CDECOL NUMBER(2, 0),
  CAU_CDESIN NUMBER(2, 0),
  CAU_TELEFN NUMBER(9, 0),
  CONSTRAINT STH_CAU_PK PRIMARY KEY
  (
    CAU_CODIGO
  )
);

COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_DENCAS IS 'Denominacion castellano';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_DENCAT IS 'Denominacion catalán';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_DORCAS IS 'Denominación organismo en castellano';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_DORCAT IS 'Denominación organismo en catalán';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_DIRECC IS 'Dirección organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_CODPOS IS 'Codigo Postal organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_CODPRO IS 'Provincia organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_CODMUN IS 'Codigo municipio del organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_CDECOL IS 'Codigo ecol organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_CDESIN IS 'Codigo esin organismo';
COMMENT ON COLUMN SISTRAHELP.STH_DCOMAU.CAU_TELEFN IS 'Telefono organismo';

CREATE TABLE SISTRAHELP.STH_DPROVI
(
  PRO_CODIGO NUMBER(2, 0) NOT NULL,
  PRO_CODCAU NUMBER(2, 0),
  PRO_DENCAS VARCHAR2(25 CHAR),
  PRO_DENCAT VARCHAR2(25 CHAR),
  CONSTRAINT STH_PRO_PK PRIMARY KEY (PRO_CODIGO),
  CONSTRAINT STH_PROCAU_FK FOREIGN KEY (PRO_CODCAU)
    REFERENCES SISTRAHELP.STH_DCOMAU (CAU_CODIGO)
);

CREATE TABLE SISTRAHELP.STH_DPAIS 
(
  PAI_CODIGO NUMBER(3, 0) NOT NULL,
  PAI_CODALF CHAR(3 CHAR) NOT NULL,
  PAI_DENCAS VARCHAR2(50 CHAR) NOT NULL,
  PAI_DENCAT VARCHAR2(50 CHAR) NOT NULL,
  PAI_VIGENC CHAR(1 CHAR) NOT NULL,
  PAI_COD2AF CHAR(3 CHAR),
  CONSTRAINT STH_PAI_PK PRIMARY KEY (PAI_CODIGO)
);

CREATE TABLE SISTRAHELP.STH_DMUNIC
(
  MUN_CODIGO NUMBER(3, 0) NOT NULL,
  MUN_PROVIN NUMBER(2, 0) NOT NULL,
  MUN_DENOFI VARCHAR2(50 CHAR) NOT NULL,
  CONSTRAINT STH_MUN_PK PRIMARY KEY
  (
    MUN_CODIGO,
    MUN_PROVIN
  ),
  CONSTRAINT STH_MUNPRO_FK FOREIGN KEY
  (
    MUN_PROVIN
  )
  REFERENCES SISTRAHELP.STH_DPROVI
  (
    PRO_CODIGO
  )
);

COMMENT ON COLUMN SISTRAHELP.STH_DMUNIC.MUN_CODIGO IS 'Codigo de municipio';
COMMENT ON COLUMN SISTRAHELP.STH_DMUNIC.MUN_PROVIN IS 'Codigo de provincia';
COMMENT ON COLUMN SISTRAHELP.STH_DMUNIC.MUN_DENOFI IS 'Denominación Oficial';

CREATE TABLE SISTRAHELP.STH_DISLAS
(
  ISL_CODIGO NUMBER(2, 0) NOT NULL,
  ISL_DENOM VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT STH_ISL_PK PRIMARY KEY
  (
    ISL_CODIGO
  )
);

COMMENT ON COLUMN SISTRAHELP.STH_DISLAS.ISL_CODIGO IS 'CODIGO ISLA';
COMMENT ON COLUMN SISTRAHELP.STH_DISLAS.ISL_DENOM IS 'NOMBRE ISLA';
COMMENT ON TABLE SISTRAHELP.STH_DISLAS IS 'Islas de baleares';

CREATE TABLE SISTRAHELP.STH_DMUISL
(
  MUI_CODISL NUMBER(2, 0) NOT NULL,
  MUI_CODMUN NUMBER(3, 0) NOT NULL,
  MUI_CODPRO NUMBER(2, 0) NOT NULL,
  CONSTRAINT STH_MUI_PK PRIMARY KEY
  (
    MUI_CODISL,
    MUI_CODMUN,
    MUI_CODPRO
  ),
  CONSTRAINT STH_MUIISL_FK FOREIGN KEY
  (
    MUI_CODISL
  )
  REFERENCES SISTRAHELP.STH_DISLAS
  (
    ISL_CODIGO
  ),
  CONSTRAINT STH_MUIMUN_FK FOREIGN KEY
  (
    MUI_CODMUN,
    MUI_CODPRO
  )
  REFERENCES SISTRAHELP.STH_DMUNIC
  (
    MUN_CODIGO,
    MUN_PROVIN
  )
);

COMMENT ON COLUMN SISTRAHELP.STH_DMUISL.MUI_CODISL IS 'CODIGO ISLA';
COMMENT ON COLUMN SISTRAHELP.STH_DMUISL.MUI_CODMUN IS 'CODIGO MUNICIPIO';
COMMENT ON COLUMN SISTRAHELP.STH_DMUISL.MUI_CODPRO IS 'CODIGO PROVINCIA';
COMMENT ON TABLE SISTRAHELP.STH_DMUISL IS 'Relacion entre municipios e islas de baleares';

GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DCOMAU TO WWW_SISTRAHELP;
GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DPROVI TO WWW_SISTRAHELP;
GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DPAIS TO WWW_SISTRAHELP;
GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DMUNIC TO WWW_SISTRAHELP;
GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DISLAS TO WWW_SISTRAHELP;
GRANT SELECT, DELETE, INSERT, UPDATE ON STH_DMUISL TO WWW_SISTRAHELP;