ALTER TABLE STG_FORCTX RENAME COLUMN CTX_NUMRMI TO CTX_NUMRMI_OLD;
ALTER TABLE STG_FORCTX RENAME COLUMN CTX_NUMRMX TO CTX_NUMRMX_OLD;

ALTER TABLE STG_FORCTX RENAME COLUMN CTX_NUMRMI_NEW TO CTX_NUMRMI;
ALTER TABLE STG_FORCTX RENAME COLUMN CTX_NUMRMX_NEW TO CTX_NUMRMX;
