CREATE TABLE SISTRAGES.STG_DOMENT_BCK AS SELECT * FROM SISTRAGES.STG_DOMENT;
CREATE TABLE SISTRAGES.STG_AREDOM_BCK AS SELECT * FROM SISTRAGES.STG_AREDOM;
CREATE TABLE SISTRAGES.STG_DOMINI_BCK AS SELECT * FROM SISTRAGES.STG_DOMINI;

GRANT SELECT, DELETE, INSERT, UPDATE ON SISTRAGES.STG_DOMENT_BCK TO WWW_SISTRAGES;
GRANT SELECT, DELETE, INSERT, UPDATE ON SISTRAGES.STG_AREDOM_BCK TO WWW_SISTRAGES;
GRANT SELECT, DELETE, INSERT, UPDATE ON SISTRAGES.STG_DOMINI_BCK TO WWW_SISTRAGES;
