/* Hacer el identificador de tramite más grande ya que es ID_ENTIDAD.ID_AREA.ID_TRAMITE */
ALTER TABLE STT_TRAPER MODIFY TRP_IDETRA VARCHAR2(100 CHAR);
ALTER TABLE STT_FORMUL MODIFY SFR_IDTRAM VARCHAR2(100 CHAR);
ALTER TABLE STT_TRAFIN MODIFY TRF_IDETRA VARCHAR2(100 CHAR);
ALTER TABLE STT_FORMUL MODIFY SFR_IDGFE VARCHAR2(100 CHAR);
