# Conexion BBDD
jdbc.jndi=java:/es.caib.sistrages.db
hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

# Entorno: des,pre,pro,se
#entorno=se
entorno=se

sistrahelp.view.url=https://ibenred2.indra.es/sistrahelp/secure/app

#promocioSe2Pro=false
promocioSe2Pro=true

# Almacenamiento ficheros
ficherosExternos.path=/opt/caib-data/sistra2-data/files_des

#jdni path
jndi.path=java:/

#migracion sistra1
jndi.migracion.sistra=java:/es.caib.sistra.db
jndi.migracion.formrol=java:/es.caib.formrol.db

admetreServeis=true
sistrages.modoEntrega.habilitar=true

#API EXTERNA STT
sistramit.rest.externa.url=https://localhost:58080/sistramitws/rest/externa/v1
sistramit.rest.externa.user=api-stt
sistramit.rest.externa.pwd=1234

# Script engine: javascript (defecto JDK, para JDK8 nashorn) / rhino
scriptEngine=rhino
